### ISSUE TITLE
TypeError on startup

### ISSUE THREAD

**Issue by corsa** [shobrook/BitVision#229]
Getting the following error on startup under macOS Mojave 10.14.2 with node v11.6.0 (also tried v10.15.0) and python  3.7.2. Check and all dependencies are installed under pip3.

`    Fetching price data from Bitstamp...
      Fetching blockchain network data...
      Fetching Bitcoin-related headlines...
      Fetching transaction history from Bitstamp...
TypeError: Cannot read property 'data' of null
    at refreshInterface (/Users/eric/.nvm/versions/node/v11.6.0/lib/node_modules/bitvision/index.js:518:36)
    at checkDependencies (/Users/eric/.nvm/versions/node/v11.6.0/lib/node_modules/bitvision/index.js:662:5)
    at checkDependencies (/Users/eric/.nvm/versions/node/v11.6.0/lib/node_modules/bitvision/index.js:634:5)
    at main (/Users/eric/.nvm/versions/node/v11.6.0/lib/node_modules/bitvision/index.js:655:3)
    at Object.<anonymous> (/Users/eric/.nvm/versions/node/v11.6.0/lib/node_modules/bitvision/index.js:672:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)`

**Comment by lietzmk** [comment]
I have the same problem. I was able to get around it by downloading all the json files in the store folder to /usr/local/lib/node_modules/bitvision/store

**Comment by neoromantic** [comment]
Same here, @lietzmk workaround helped.

**Comment by alichtman** [comment]
Fixed in v1.1.7
