### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by QuantumTarantino** [shobrook/BitVision#232]
I get the following error on launch. I'm using Ubuntu Mate Desktop 18.04

/usr/local/lib/node_modules/bitvision/index.js:620
  }).output[1];
           ^

TypeError: Cannot read property '1' of null
    at checkDependencies (/usr/local/lib/node_modules/bitvision/index.js:620:12)
    at main (/usr/local/lib/node_modules/bitvision/index.js:683:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/bitvision/index.js:700:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by QuantumTarantino** [comment]
Checking the code, the error comes when Bitvision is executed for first time. The error is related with this piece of code:

function checkDependencies(callback) {
  let uninstalledDeps = [];
  let requirements = fs.readFileSync(filePaths.requirementsPath, "utf8");
  let currDeps = spawnSync("pip3", ["list"], {
    cwd: process.cwd(),
    env: process.env,
    stdio: "pipe",
    encoding: "utf-8"
  }).output[1];

Checking if I had pip3 package installed I saw that only pip package was installed.

Putting on console:
`sudo apt install python3-pip`
should be enough.

Now works for me.

**Comment by alichtman** [comment]
Yep, pip3 is a requirement to run this package. Glad you found a solution.

**Comment by alichtman** [comment]
@shobrook Do we wanna print an error if the command fails because pip3 isn't found?
