### ISSUE TITLE
Tabbing to username field crashes application

### ISSUE THREAD

**Issue by joeyfigaro** [shobrook/BitVision#243]
Tabbing to the first field in the bitstamp setup modal causes the application to throw the following:

```js
TypeError: done is not a function
    at Textbox.Textarea._listener (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/widgets/textarea.js:231:5)
    at Textbox._listener (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/widgets/textbox.js:43:15)
    at Textbox.EventEmitter._emit (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/events.js:98:20)
    at Textbox.EventEmitter.emit (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/events.js:117:12)
    at Form.<anonymous> (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/widgets/form.js:43:14)
    at Form.EventEmitter._emit (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/events.js:94:20)
    at Textbox.EventEmitter.emit (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/events.js:131:12)
    at Program.<anonymous> (/Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/widgets/screen.js:602:15)
    at Program.emit (events.js:189:13)
    at /Users/joeyfigaro/.config/yarn/global/node_modules/blessed/lib/program.js:410:15
```

**Comment by alichtman** [comment]
Weird. I've never seen this happen before. I guess I'll leave this open.
