### ISSUE TITLE
store path missing - initial startup failure

### ISSUE THREAD

**Issue by nuzz** [shobrook/BitVision#246]
I followed the installation in the readme and bitvision fails to start, the 

`Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/bitvision/store/config.json'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1210:35)
    at writeJSONFile (/usr/local/lib/node_modules/bitvision/index.js:49:6)
    at createConfig (/usr/local/lib/node_modules/bitvision/index.js:94:5)
    at checkDependencies (/usr/local/lib/node_modules/bitvision/index.js:717:5)
    at checkDependencies (/usr/local/lib/node_modules/bitvision/index.js:690:5)
    at main (/usr/local/lib/node_modules/bitvision/index.js:713:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/bitvision/index.js:734:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)`

I took a guess and just mkdir'd /usr/local/bin/bitvision/store and everything started

**Comment by schoreZ** [comment]
I had the same problem when starting:

```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/bitvision/store/config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at writeJSONFile (/usr/local/lib/node_modules/bitvision/index.js:49:6)
    at createConfig (/usr/local/lib/node_modules/bitvision/index.js:94:5)
    at checkDependencies (/usr/local/lib/node_modules/bitvision/index.js:717:5)
    at checkDependencies (/usr/local/lib/node_modules/bitvision/index.js:690:5)
    at main (/usr/local/lib/node_modules/bitvision/index.js:713:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/bitvision/index.js:734:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

```

**Comment by filipiz** [comment]
+1

**Comment by joafalves** [comment]
Same here! Also, the dependency missing warning appears every time the app is initiated.

**Comment by hmehd** [comment]
if your dependencies are good is good, try this

node index.js
