### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by scottie** [shobrook/BitVision#247]
simply installing using NPM global install and having python and nodejs upto date does not work.

Screenshot:
https://i.imgur.com/Eq2m6P8.png

Python: 3.7.2
Node: 10.15.1

```
AppData\Roaming\npm\node_modules\bitvision\index.js:648
  }).output[1];
           ^

TypeError: Cannot read property '1' of null
    at checkDependencies (C:\Users\console\AppData\Roaming\npm\node_modules\bitvision\index.js:648:12)
    at main (C:\Users\console\AppData\Roaming\npm\node_modules\bitvision\index.js:713:3)
    at Object.<anonymous> (C:\Users\console\AppData\Roaming\npm\node_modules\bitvision\index.js:734:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by alichtman** [comment]
This was designed for *nix systems, and probably won't work on Windows without a bunch of effort. I can pretty confidently say that I'll never run Windows, and neither will @shobrook, so this isn't on our to-do list. If you want to write Windows support, that'd definitely be appreciated. However, this issue won't be addressed by us.

**Comment by scottie** [comment]
Rodger that

**Comment by scottie** [comment]
Just so you know the same error happens on Linux, Ubuntu 16.

![image](https://user-images.githubusercontent.com/94546/55763679-51375900-5aab-11e9-8b82-597b55e232a6.png)

```
root@bit:~# node --version
v11.13.0
root@bit:~# python --version
Python 2.7.12
root@bit:~# python3.7 --version
Python 3.7.3
```

**Comment by caork** [comment]
still the same error
