### ISSUE TITLE
TypeError: Cannot read property 'data' of null

### ISSUE THREAD

**Issue by michaelp433809** [shobrook/BitVision#256]
Using CMD entering "bitvision" program starts up and attempts to fetch price data, blockchain network data, bitcoin related headlines, and transaction history, then throws this error at me:

```
TypeError: Cannot read property 'data' of null
    at refreshInterface (C:\Users\xboxm\AppData\Roaming\npm\node_modules\bitvision\index.js:557:36)
    at C:\Users\xboxm\AppData\Roaming\npm\node_modules\bitvision\index.js:724:5
    at checkDependencies (C:\Users\xboxm\AppData\Roaming\npm\node_modules\bitvision\index.js:690:5)
    at main (C:\Users\xboxm\AppData\Roaming\npm\node_modules\bitvision\index.js:713:3)
    at Object.<anonymous> (C:\Users\xboxm\AppData\Roaming\npm\node_modules\bitvision\index.js:734:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

**Comment by boblebeub** [comment]
Same issue. I'm trying to learn a bit about programming.

**Comment by bigo72** [comment]
Guys, I'm fighting with this piece of software from 2 hours....I'm a bit tired. Can we say that it just doesn't work?
